; Build do firmware (um único binário do Arduino).
; Ajustar 'board' e 'platform' conforme a placa usada (ex.: Arduino Mega 2560).

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
monitor_echo = yes
monitor_filters = send_on_enter, colorize
lib_deps =
    hideakitai/TCS34725
; lib_deps =
;     ; TODO: bibliotecas (ex.: driver do TCS34725, etc.)
